name: Github actions for AWS and TF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      # Setup TF 
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      
      # Authenticate to Cloud
      - name: "Configure to AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      # # Terraform actions
      - name : "Terraform Initializaton"
        run: terraform init

      # - name: "Terraform validate"
      #   run:  terraform validate

      # - name: "Planning the infra"
      #   run: terraform plan -lock=false

      # - name: "Terraform apply"
      #   run:  terraform apply --auto-approve -lock=false

      - name: "Terraform destroy"
        run:  terraform destroy --auto-approve -lock=false
